### ISSUE TITLE
TAP Support

### ISSUE THREAD

**Issue by gwn** [okwolf/tead#18]
Hello. Great library. I'm not sure if [TAP](https://en.wikipedia.org/wiki/Test_Anything_Protocol) is supported. If it is not, why not support it, as it is a standard protocol and being used by nearly all other sweet minimalistic testing libraries?

Another benefit would be to compose `tead` with other TAP supporting utilities already available.

**Comment by okwolf** [comment]
@gwn alternate output formats are not currently supported, but if that does land TAP would be a great custom reporter to write. See #11.

**Comment by okwolf** [comment]
@gwn if you wish to keep pushing this proposal forward, please do so in existing issue #11.
